name: LaTeX
on: [push]
# on:
#   push:
#     paths: CV-PS/
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: "CV_*.tex"
          working_directory: CV-PS/
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: CV-PS
          path: "*.pdf"
