name: LaTeX
on:
  push:
    paths:
      - ".github/workflows/LaTeX.yml"
      - "CV-PS/*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: |
            CV_en.tex
            CV_zh.tex
            PS_scholarship_old.tex
            PS_scholarship.tex
            PS_slide.tex
            PS.tex
          working_directory: CV-PS/
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: CV-PS
          path: |
            CV-PS/CV_en.pdf
            CV-PS/CV_zh.pdf
            CV-PS/PS_scholarship_old.pdf
            CV-PS/PS_scholarship.pdf
            CV-PS/PS_slide.pdf
            CV-PS/PS.pdf
